### ISSUE TITLE
401 Unauthorized / 404 Not Found / Cannot iterate over null

### ISSUE THREAD

**Issue by pstadler** [pstadler/ticker.sh#37]
Here we go again.
More information in #33. Fix available in branch [acquire-yahoo-finance-session](https://github.com/pstadler/ticker.sh/tree/acquire-yahoo-finance-session)

**Comment by pcause** [comment]
tried that version and same jq error.

**Comment by amccombsahce** [comment]
I know nothing, but I edited ticker.sh and changed line API_ENDPOINT, and replaced "v7" with "v6", and that appears to return a result; I guess I just got lucky.

**Comment by pstadler** [comment]
Interesting. Will test things later. I‘m currently undecided what to do next. Last time the problem went away.

**Comment by pcause** [comment]
i just made it v6 and that worked

**Comment by pstadler** [comment]
released a new version using v6. thanks folks!

**Comment by pstadler** [comment]
It looks like the workaround using v6 stopped working. [acquire-yahoo-finance-session](https://github.com/pstadler/ticker.sh/tree/acquire-yahoo-finance-session) is probably the way to go.

**Comment by justinodunn** [comment]
> It looks like the workaround using v6 stopped working. [acquire-yahoo-finance-session](https://github.com/pstadler/ticker.sh/tree/acquire-yahoo-finance-session) is probably the way to go.

Do you know if acquiring crumbs and cookies for the v6 url works? Or is it only working for v7?

Because if this isn't a crumb / cookie issue with v6, maybe they're just having problems in the backend and will most likely be fixed when the Yahoo team is awake.

**Comment by pstadler** [comment]
Yeah, I'm definitely waiting before releasing a fix.

**Comment by tomaszg7** [comment]
I didn't look at the code, but as far as I know https://github.com/premnirmal/StockTicker also uses Yahoo data and it is still working. Might be worthwhile to take a look there. It was broken just like this script last month when the issue first surfaced. Maybe they figured out some fix.

**Comment by pstadler** [comment]
Just merged #39 
This won't work in some countries due to checks for cookie consent. Unfortunately, I can't reproduce it on my side, so I'd need your help to handle this case.

**Comment by g4570n** [comment]
> Just merged #39
> This won't work in some countries due to checks for cookie consent. Unfortunately, I can't reproduce it on my side, so I'd need your help to handle this case.

With this change it is working for me now. I am in south america.

**Comment by pcause** [comment]
fixed for me as well

**Comment by tomaszg7** [comment]
> Just merged #39 This won't work in some countries due to checks for cookie consent. Unfortunately, I can't reproduce it on my side, so I'd need your help to handle this case.

Not fixed for me, as expected :) I'm still troubled by georestriction issue. Let me know if you have any idea how I could help.

**Comment by PSLLSP** [comment]
It still doesn't work for me. I cannot get file crump.txt, ticker.sh script fetch "Server error 500" (long file with css, etc to show error 500). When I try in my browser, I get code, like "C5CDSr9vMve", I assume that something like this should be in crump.txt. When I examine cookies.txt, I see just one entry, like
`.yahoo.com	TRUE	/	TRUE	1685652033	GUCS	AXbWBsEE`

I run Linux and I am in EU...

**Comment by jeandupont314** [comment]
Still no solution for me:
ticker.sh  ASML.AS
jq: error (at <stdin>:1): Cannot iterate over null (null)

I run Linux too and I am in the EU too

**Comment by pcause** [comment]
working for me here in US.

**Comment by peterhorsley** [comment]
working for me in Australia.

**Comment by giuli007** [comment]
I was experiencing similar issues being reported here and on https://github.com/pstadler/ticker.sh/issues/33

Symptoms are that:
-  the initial request (https://github.com/pstadler/ticker.sh/blob/2ac6837f5275682bf63bd75dd9ef7b4a9ac20a3e/ticker.sh#L41) to `https://finance.yahoo.com` gets redirected, as mentioned [here](https://github.com/pstadler/ticker.sh/issues/33#issuecomment-1517340591) and doesn't set the cookie properly
- which means that the subsequent request (https://github.com/pstadler/ticker.sh/blob/2ac6837f5275682bf63bd75dd9ef7b4a9ac20a3e/ticker.sh#L43) to get the crumb returns a 500 error page
- which is then used as a query parameter (even though it's a multiline HTML doc) on the request to get quotes (https://github.com/pstadler/ticker.sh/blob/2ac6837f5275682bf63bd75dd9ef7b4a9ac20a3e/ticker.sh#L48) and causes curl to just fail silently

After looking around a bit and reading on [this StackOverflow answer](https://stackoverflow.com/a/76320367) I noticed it suggest using https://fc.yahoo.com/ instead of https://finance.yahoo.com/ to get the cookie.
I tried simply changing that url on ticker.sh and it works!
```diff
diff --git a/ticker.sh b/ticker.sh
index f2ffe6c..a84f5a1 100755
--- a/ticker.sh
+++ b/ticker.sh
@@ -38,7 +38,7 @@ fields=$(IFS=,; echo "${FIELDS[*]}")
 [ ! -d "$SESSION_DIR" ] && mkdir -m 700 "$SESSION_DIR"

 preflight () {
-  curl --silent --output /dev/null --cookie-jar "$COOKIE_FILE" "https://finance.yahoo.com" \
+  curl --silent --output /dev/null --cookie-jar "$COOKIE_FILE" "https://fc.yahoo.com" \
   -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
   curl --silent -b "$COOKIE_FILE" "https://query1.finance.yahoo.com/v1/test/getcrumb" \
     > "$CRUMB_FILE"
```

I don't know how reliable this is going to be in the long term, as I am not sure if yahoo makes any guarantee about this url not redirecting, but it seem to be an effective workaround for now and I just thought it would be worth sharing it. cc @pstadler

**Comment by pstadler** [comment]
@giuli007 wow, this is great! would you mind opening a PR?

**Comment by giuli007** [comment]
> @giuli007 wow, this is great! would you mind opening a PR?

Sure! There you go https://github.com/pstadler/ticker.sh/pull/42

**Comment by pstadler** [comment]
Awesome, thanks a lot!

@tomaszg7 @PSLLSP @jeandupont314 could you please confirm whether the fix in #42 is working for you?

**Comment by tomaszg7** [comment]
It does. I just had to remember to delete old /tmp/ticker* which kept broken cookie from previous runs.

**Comment by jeandupont314** [comment]
> Awesome, thanks a lot!
> 
> @tomaszg7 @PSLLSP @jeandupont314 could you please confirm whether the fix in #42 is working for you?

It works again, thanks!

**Comment by dropbrick** [comment]
Anyone getting this again ?

**Comment by tomaszg7** [comment]
I was getting empty output again, had to remove manually `/tmp/ticker*` again to fix it.

**Comment by dropbrick** [comment]
I am getting this again, inside /tmp/ticker.sh-username/crumb.txt I get "Too Many Requests"

**Comment by g4570n** [comment]
> I am getting this again, inside /tmp/ticker.sh-username/crumb.txt I get "Too Many Requests"

the same thing happens here too

**Comment by pstadler** [comment]
#45
